name: Build & Release WirePeek-WebPro

on:
  push:
    tags:
      - "v*.*.*"   # ex.: v1.0.0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --name WirePeek-WebPro src/main.py

      - name: Install WiX Toolset
        shell: pwsh
        run: choco install wixtoolset --no-progress -y

      - name: Build MSI
        shell: pwsh
        run: |
          candle.exe deploy/product.wxs -o product.wixobj
          light.exe product.wixobj -o WirePeek-WebPro.msi

      - name: Prepare release folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release | Out-Null
          Copy-Item dist/WirePeek-WebPro.exe release/
          Copy-Item WirePeek-WebPro.msi release/
          if (Test-Path guia_instalacao_compilacao.pdf) { Copy-Item guia_instalacao_compilacao.pdf release/ }
          if (Test-Path INSTALL.md) { Copy-Item INSTALL.md release/ }

      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v4
        with:
          name: WirePeek-WebPro-bin
          path: release/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: WirePeek-WebPro-bin
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/WirePeek-WebPro.exe
            release/WirePeek-WebPro.msi
            release/guia_instalacao_compilacao.pdf
            release/INSTALL.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
